apiVersion: v1
kind: Secret
metadata:
  name: autohub-secrets
type: Opaque
stringData:
  internalApiSecret: {{ .Values.internalApiSecret | quote }}
  postgresPassword: {{ .Values.postgres.password | quote }}
  rabbitmqUser: {{ .Values.rabbitmq.user | quote }}
  rabbitmqPassword: {{ .Values.rabbitmq.password | quote }}
  jwtPrivateKeyPem: {{ .Values.auth.jwtPrivateKeyPem | quote }}
