apiVersion: v1
kind: Secret
metadata:
  name: autohub-secrets
type: Opaque
stringData:
  internalApiSecret: {{ .Values.internalApiSecret }}
  postgresPassword: {{ .Values.postgres.password }}
  rabbitmqUser: {{ .Values.rabbitmq.user }}
  rabbitmqPassword: {{ .Values.rabbitmq.password }}
