{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: autohub-{{ $name }}
spec:
  selector:
    app: autohub-{{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
{{- end }}
